version: "3.9" #optional since 1.27.0
services:
  app:
    build:
      args:
        user: ragnabott_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ragnabott-pool
    container_name: ragnabott-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
    - ./:/var/www
    networks:
      - ragnabott
  db:
    image: postgres:14.2-alpine
    container_name: ragnabott-db
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

      #POSTGRES_INITDB_ARGS:
      #POSTGRES_INITDB_WALDIR: #TRANSACTION LOG
      #PGDATA: #optional for defining alternate location for db files, default is /var/lib/postgresql/data, must be chowned to postgres user
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes:
      - ./docker/config/pgsql:docker-entrypoint-initdb.d
    networks:
      - ragnabott
  nginx:
    image: nginx:alpine
    container_name: ragnabott-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ragnabott
networks:
  ragnabott:
    driver: bridge
#volumes: